//
//  SearchPresenter.swift
//  EatAndFork
//
//  Created by Visarut on 6/7/2566 BE.
//  Copyright (c) 2566 BE Newfml. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchPresentationLogic {
    func presentFilterMenuItems(response: Search.Filter.Response)
}

class SearchPresenter: SearchPresentationLogic {
    weak var viewController: SearchDisplayLogic?

    // MARK: Parse and calc respnse from SearchInteractor and send simple view model to SearchViewController to be displayed

    func presentFilterMenuItems(response: Search.Filter.Response) {
        viewController?.displayFilterMenuItems(
            viewModel: .init(
                menuItems: response.menuItems
            )
        )
    }
}
