//
//  SearchPresenter.swift
//  EatAndFork
//
//  Created by Visarut on 6/7/2566 BE.
//  Copyright (c) 2566 BE Newfml. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchPresentationLogic {
    func presentFilterMenuItems(response: Search.Filter.Response)
}

final class SearchPresenter: SearchPresentationLogic {
    weak var viewController: SearchDisplayLogic?

    func presentFilterMenuItems(response: Search.Filter.Response) {
        let viewModels = response.menuItems.compactMap { item in
            ItemViewModel(
                imageUrl: item.imageUrl,
                name: item.name,
                price: item.price.description.Baht(),
                numberOfItem: nil
            )
        }
        viewController?.displayFilterMenuItems(
            viewModel: .init(
                itemViewModels: viewModels
            )
        )
    }
}
