//
//  SearchWorker.swift
//  EatAndFork
//
//  Created by Visarut on 6/7/2566 BE.
//  Copyright (c) 2566 BE Newfml. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SearchWorker {
    func filterMenuItemsByText(searchText: String, menuItems: [MenuItem]) -> [MenuItem] {
        guard searchText.isEmpty != true else { return menuItems }
        let filterMenuItems = menuItems.filter { menuItem in
            return menuItem.name.contains(searchText)
        }
        return filterMenuItems
    }
}
