//
//  MainRouter.swift
//  EatAndFork
//
//  Created by Visarut on 4/7/2566 BE.
//  Copyright (c) 2566 BE Newfml. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MainRoutingLogic {
    func routeToSearch()
    func routeToItemDetail(index: Int)
    func routeToSummary()
}

protocol MainDataPassing {
    var dataStore: MainDataStore? { get }
}

final class MainRouter: MainRoutingLogic, MainDataPassing {
    weak var viewController: MainViewController?
    var dataStore: MainDataStore?
    
    func routeToSearch() {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let searchViewController = storyboard.instantiateViewController(withIdentifier: "SearchViewController") as! SearchViewController
        searchViewController.interactor?.menuItems = dataStore?.menuItems ?? []
        viewController?.navigationController?.pushViewController(searchViewController, animated: true)
    }
    
    func routeToItemDetail(index: Int) {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let detailViewController = storyboard.instantiateViewController(withIdentifier: "DetailViewController") as! DetailViewController
        detailViewController.interactor?.menuItem = dataStore?.menuItems[index]
        detailViewController.modalPresentationStyle = .fullScreen
        viewController?.present(detailViewController, animated: true)
    }
    
    func routeToSummary() {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let summaryViewController = storyboard.instantiateViewController(withIdentifier: "SummaryViewController") as! SummaryViewController
        viewController?.navigationController?.pushViewController(summaryViewController, animated: true)
    }
}
