//
//  MainInteractor.swift
//  EatAndFork
//
//  Created by Visarut on 4/7/2566 BE.
//  Copyright (c) 2566 BE Newfml. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainBusinessLogic {
    func fetchMemuItems(request: Main.FetchMenus.Request)
}

protocol MainDataStore {
    var menuItems: [MenuItem] { get set }
}

class MainInteractor: MainBusinessLogic, MainDataStore {
    var menuItems: [MenuItem] = []
    
    var presenter: MainPresentationLogic?
    private var worker: MainWorker = MainWorker()

    // MARK: Do something (and send response to MainPresenter)

    func fetchMemuItems(request: Main.FetchMenus.Request) {
        worker.fetchMenuItems { [weak self] response in
            self?.menuItems = response
            DispatchQueue.main.async {
                self?.presenter?.presentMenuItems(response: .init())
            }
        }
    }
}
