//
//  MainModels.swift
//  EatAndFork
//
//  Created by Visarut on 4/7/2566 BE.
//  Copyright (c) 2566 BE Newfml. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Main {
    enum Section: Int, CaseIterable {
        case search = 0, menus
    }
    
    // MARK: Use cases
    
    enum FetchMenus {
        struct Request {}
        
        struct ViewModel {}
        
        struct Response {}
    }
}
