//
//  MainPresenter.swift
//  EatAndFork
//
//  Created by Visarut on 4/7/2566 BE.
//  Copyright (c) 2566 BE Newfml. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic {
    func presentMenuItems(response: Main.FetchMenus.Response)
}

class MainPresenter: MainPresentationLogic {
    weak var viewController: MainDisplayLogic?
    
    // MARK: Parse and calc respnse from MainInteractor and send simple view model to MainViewController to be displayed
    
    func presentMenuItems(response: Main.FetchMenus.Response) {
        viewController?.displayMenuItems(viewModel: .init())
    }
}
