//
//  MainRouter.swift
//  EatAndFork
//
//  Created by Visarut on 4/7/2566 BE.
//  Copyright (c) 2566 BE Newfml. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MainRoutingLogic {
    func routeToSearch()
    func routeToItemDetail(index: Int)
    func routeToSummary()
}

protocol MainDataPassing {
    var dataStore: MainDataStore? { get }
}

final class MainRouter: NSObject, MainRoutingLogic, MainDataPassing {
    weak var viewController: MainViewController?
    var dataStore: MainDataStore?
    
    func routeToSearch() {
        guard let viewController = viewController else { return }
        let searchViewController = SearchViewController()
        searchViewController.interactor?.menuItems = dataStore?.menuItems ?? []
        viewController.navigationController?.pushViewController(searchViewController, animated: true)
    }
    
    func routeToItemDetail(index: Int) {
        guard let viewController = viewController else { return }
        let detailViewController = DetailViewController()
        detailViewController.interactor?.menuItem = dataStore?.menuItems[index]
        detailViewController.modalPresentationStyle = .fullScreen
        viewController.present(detailViewController, animated: true)
    }
    
    func routeToSummary() {
        guard let viewController = viewController else { return }
        let summaryViewController = SummaryViewController()
        viewController.navigationController?.pushViewController(summaryViewController, animated: true)
    }
}
