//
//  SummaryInteractor.swift
//  EatAndFork
//
//  Created by Visarut on 7/7/2566 BE.
//  Copyright (c) 2566 BE Newfml. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SummaryBusinessLogic {
    func fetchData(request: Summary.FetchData.Request)
    func deleteItem(request: Summary.DeleteItem.Request)
}

protocol SummaryDataStore {
    
}

final class SummaryInteractor: SummaryBusinessLogic, SummaryDataStore {
    var presenter: SummaryPresentationLogic?

    private let cartManager: CartManagerProtocol = CartManager.shared

    func fetchData(request: Summary.FetchData.Request) {
        let cartItems = cartManager.getAllItems()
        let totalPrice = cartManager.getTotalPrice()
        presenter?.presentData(
            response: .init(
                cartItems: cartItems,
                totalPrice: totalPrice
            )
        )
    }
    
    func deleteItem(request: Summary.DeleteItem.Request) {
        cartManager.deleteItem(index: request.index)
        let cartItems = cartManager.getAllItems()
        let totalPrice = cartManager.getTotalPrice()
        presenter?.presentData(
            response: .init(
                cartItems: cartItems,
                totalPrice: totalPrice
            )
        )
    }
}
