//
//  SummaryInteractor.swift
//  EatAndFork
//
//  Created by Visarut on 7/7/2566 BE.
//  Copyright (c) 2566 BE Newfml. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SummaryBusinessLogic {
    func fetchData(request: Summary.FetchData.Request)
    func deleteItem(request: Summary.DeleteItem.Request)
}

final class SummaryInteractor: SummaryBusinessLogic {
    var presenter: SummaryPresentationLogic?
    
    private var cartItems: [CartItem] {
        return cartManager.getAllItems()
    }
    
    private var totalPriceOfItems: Double {
        return cartManager.getTotalPriceOfItems()
    }
    
    private var serviceCharge: Double {
        return cartManager.getServiceCharge()
    }
    
    private var vat: Double {
        return cartManager.getVat()
    }
    
    private var totalPrice: Double {
        return cartManager.getTotalPriceWithExtra()
    }
    
    private let cartManager: CartManagerProtocol
    
    init(cartManager: CartManagerProtocol = CartManager.shared) {
        self.cartManager = cartManager
    }

    func fetchData(request: Summary.FetchData.Request) {
        presenter?.presentData(
            response: .init(
                cartItems: cartItems,
                totalPriceOfItems: totalPriceOfItems,
                serviceCharge: serviceCharge,
                vat: vat,
                totalPrice: totalPrice
            )
        )
    }
    
    func deleteItem(request: Summary.DeleteItem.Request) {
        cartManager.deleteItem(index: request.index)
        presenter?.presentData(
            response: .init(
                cartItems: cartItems,
                totalPriceOfItems: totalPriceOfItems,
                serviceCharge: serviceCharge,
                vat: vat,
                totalPrice: totalPrice
            )
        )
    }
}
