//
//  SummaryModels.swift
//  EatAndFork
//
//  Created by Visarut on 7/7/2566 BE.
//  Copyright (c) 2566 BE Newfml. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Summary {
    enum Section: Int, CaseIterable, Hashable {
        case items = 0, priceDetail
    }
    
    enum Row: Hashable {
        case items(SummaryItemListViewModel)
        case priceDetail(PriceDetailViewModel)
    }
    
    // MARK: Use cases

    enum FetchData {
        struct Request {}

        struct Response {
            let cartItems: [CartItem]
            let totalPriceOfItems: Double
            let serviceCharge: Double
            let vat: Double
            let totalPrice: Double
        }

        struct ViewModel {
            let summaryItemListViewModels: [Row]
            let priceDetailViewModels: [Row]
            let totalPrice: String
        }
    }
    
    enum DeleteItem {
        struct Request {
            let index: Int
        }

        struct Response {}

        struct ViewModel  {}
    }
}
