//
//  SummaryRouter.swift
//  EatAndFork
//
//  Created by Visarut on 7/7/2566 BE.
//  Copyright (c) 2566 BE Newfml. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SummaryRoutingLogic {
    func routeToThankyou()
}

protocol SummaryDataPassing {
    var dataStore: SummaryDataStore? { get }
}

final class SummaryRouter: NSObject, SummaryRoutingLogic, SummaryDataPassing {
    weak var viewController: SummaryViewController?
    var dataStore: SummaryDataStore?
    
    private let cartManager: CartManagerProtocol = CartManager.shared
    
    // MARK: Routing (navigating to other screens)
    
    func routeToThankyou() {
        guard let viewController = viewController else { return }
        let thankyouPopupViewController = ThankYouPopupViewController()
        thankyouPopupViewController.modalPresentationStyle = .overFullScreen
        thankyouPopupViewController.modalTransitionStyle = .crossDissolve
        viewController.present(thankyouPopupViewController, animated: true)  {
            self.cartManager.clearCart()
            viewController.navigationController?.popToRootViewController(animated: false)
        }
    }
}
