//
//  SummaryRouter.swift
//  EatAndFork
//
//  Created by Visarut on 7/7/2566 BE.
//  Copyright (c) 2566 BE Newfml. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SummaryRoutingLogic {
    func routeToThankyou()
}

final class SummaryRouter: SummaryRoutingLogic {
    weak var viewController: SummaryViewController?

    private let cartManager: CartManagerProtocol
    
    init(cartManager: CartManagerProtocol = CartManager.shared) {
        self.cartManager = cartManager
    }
    
    // MARK: Routing (navigating to other screens)
    
    func routeToThankyou() {
        let thankyouPopupViewController = ThankYouPopupViewController()
        thankyouPopupViewController.modalPresentationStyle = .overFullScreen
        thankyouPopupViewController.modalTransitionStyle = .crossDissolve
        cartManager.clearCart()
        viewController?.present(thankyouPopupViewController, animated: true) { [weak self] in
            self?.viewController?.navigationController?.popToRootViewController(animated: false)
        }
    }
}
