//
//  DetailRouter.swift
//  EatAndFork
//
//  Created by Visarut on 6/7/2566 BE.
//  Copyright (c) 2566 BE Newfml. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DetailRoutingLogic {
    func routeToBrowser()
}

protocol DetailDataPassing {
    var dataStore: DetailDataStore? { get }
}

final class DetailRouter: NSObject, DetailRoutingLogic, DetailDataPassing {
    weak var viewController: DetailViewController?
    var dataStore: DetailDataStore?

// MARK: Routing (navigating to other screens)

    func routeToBrowser() {
        guard let url = URL(string: dataStore?.menuItem?.url ?? "") else { return }
        UIApplication.shared.open(url)
    }

}
